### ISSUE TITLE
React Rewrite

### ISSUE THREAD

**Issue by cofinley** [cofinley/free-roam#3]
After trying things in jQuery, I soon realized I'd need React or something more reactive if I wanted to keep track of blocks and propagate updates throughout the system. I've decided to use this as an opportunity to learn not only React, but its latest conventions.

Current, long-running todo:

- [x]  Markdown rendering of bold, underline, etc.
- [x]  Linking/hot-creating pages
    - [x]  Search on double-bracket
    - [ ]  Fix bug where changing link text changes the title of the linked page (#5)
- [x]  Showing linked references
    - [ ]  Different references view for view pane (#16)
- [x]  Sidebar on shift-click
    - [x]  Add 'X' removal button on view pane blocks
- [x]  Edit title
    - [x]  Update all linked refs with new title
- [x]  Showing unlinked references
    - [ ]  Fix bug where showing unlinked references on one page shows them on all (#6)
- [x]  Search
    - [x]  Create if none
    - [x]  Clear search input on page click
    - [x]  Search within block text as well, position these result under page title results
- [x]  Shortcuts/favoriting a page
    - [x]  If a block is pulled up, the page gets favorited
- [x]  Indenting and unindenting
    - [x]  Fix bug where focus is lost after doing so
    - [ ] Allow deleting of empty, non-title block when typing backspace (#7)
      - Only if it's not the only block left
      - If not empty, merge into closest visually-adjacent block above
- [x]  New sibling block on <Enter>
- [x]  Actions
    - [x]  Zoom in
        - [x]  Breadcrumbs
    - [x]  Show or hide thread
- [x]  Thread lines
    - [x]  Click to collapse
- [ ]  Styling (#8)
    - [ ]  Indicator of collapsed block
    - [ ]  Link colors
    - [ ]  Linked references
- [x]  Local save and load
    - [x]  Ask if user wants to stay on page when closing tab
- [ ]  Optimize cursor click → caret pos translation (#9)
    - [ ] When arrowing up/down and edge of block is reached, go to visually-adjacent block
- [ ]  Graph view (#10)
    - Use [d3-force](https://github.com/d3/d3-force#simulation_nodes) maybe?
- [ ]  All pages view (#11)
- [ ]  Daily notes (#12)
- [ ]  Resizable panes (#13)
- [ ]  Sidebar toggling (#14)
- [ ]  Markdown import/export (#15)

**Comment by cofinley** [comment]
Added new issue links for the remaining todo list items to organize it a bit more.
